name: pure-evil-web

services:
  pure-evil-web:
    build: .
    container_name: pure-evil-web
    ports:
      - "3001:3000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
